using System;

namespace SDL3
{
    public static partial class SDL
    {
        public const int ScanCodeMask = (1 << 30);
        public static KeyCode ScanCodeToKeyCode(ScanCode X) => (KeyCode)((int)X | ScanCodeMask);

        public enum KeyCode
        {
            Unknown = 0,

            Return = '\r',
            Escape = '\x1B',
            Backspace = '\b',
            Tab = '\t',
            Space = ' ',
            Exclaim = '!',
            QuoteDBL = '"',
            Hash = '#',
            Percent = '%',
            Dollar = '$',
            Ampersand = '&',
            Quote = '\'',
            LeftParen = '(',
            RightParen = ')',
            Asterisk = '*',
            Plus = '+',
            Comma = ',',
            Minus = '-',
            Period = '.',
            Slash = '/',

            Alpha0 = '0',
            Alpha1 = '1',
            Alpha2 = '2',
            Alpha3 = '3',
            Alpha4 = '4',
            Alpha5 = '5',
            Alpha6 = '6',
            Alpha7 = '7',
            Alpha8 = '8',
            Alpha9 = '9',

            Colon = ':',
            SemiColon = ';',
            Less = '<',
            Equals = '=',
            Greater = '>',
            Question = '?',
            At = '@',

            // Skip uppercase letters

            LeftBracket = '[',
            Backslash = '\\',
            RightBracket = ']',
            Caret = '^',
            Underscore = '_',
            BackQuote = '`',

            A = 'a',
            B = 'b',
            C = 'c',
            D = 'd',
            E = 'e',
            F = 'f',
            G = 'g',
            H = 'h',
            I = 'i',
            J = 'j',
            K = 'k',
            L = 'l',
            M = 'm',
            N = 'n',
            O = 'o',
            P = 'p',
            Q = 'q',
            R = 'r',
            S = 's',
            T = 't',
            U = 'u',
            V = 'v',
            W = 'w',
            X = 'x',
            Y = 'y',
            Z = 'z',

            CapsLock = ScanCode.CapsLock | ScanCodeMask,

            F1 = ScanCode.F1 | ScanCodeMask,
            F2 = ScanCode.F2 | ScanCodeMask,
            F3 = ScanCode.F3 | ScanCodeMask,
            F4 = ScanCode.F4 | ScanCodeMask,
            F5 = ScanCode.F5 | ScanCodeMask,
            F6 = ScanCode.F6 | ScanCodeMask,
            F7 = ScanCode.F7 | ScanCodeMask,
            F8 = ScanCode.F8 | ScanCodeMask,
            F9 = ScanCode.F9 | ScanCodeMask,
            F10 = ScanCode.F10 | ScanCodeMask,
            F11 = ScanCode.F11 | ScanCodeMask,
            F12 = ScanCode.F12 | ScanCodeMask,

            PrintScreen = ScanCode.PrintScreen | ScanCodeMask,
            ScrollLock = ScanCode.ScrollLock | ScanCodeMask,
            Pause = ScanCode.Pause | ScanCodeMask,
            Insert = ScanCode.Insert | ScanCodeMask,
            Home = ScanCode.Home | ScanCodeMask,
            PageUp = ScanCode.PageUp | ScanCodeMask,
            Delete = '\x7F',
            End = ScanCode.End | ScanCodeMask,
            PageDown = ScanCode.PageDown | ScanCodeMask,
            Right = ScanCode.Right | ScanCodeMask,
            Left = ScanCode.Left | ScanCodeMask,
            Down = ScanCode.Down | ScanCodeMask,
            Up = ScanCode.Up | ScanCodeMask,

            NumLockClear = ScanCode.NumLockClear | ScanCodeMask,
            KeypadDivide = ScanCode.KeypadDivide | ScanCodeMask,
            KeypadMultiply = ScanCode.KeypadMultiply | ScanCodeMask,
            KeypadMinus = ScanCode.KeypadMinus | ScanCodeMask,
            KeypadPlus = ScanCode.KeypadPlus | ScanCodeMask,
            KeypadEnter = ScanCode.KeypadEnter | ScanCodeMask,
            Keypad1 = ScanCode.Keypad1 | ScanCodeMask,
            Keypad2 = ScanCode.Keypad2 | ScanCodeMask,
            Keypad3 = ScanCode.Keypad3 | ScanCodeMask,
            Keypad4 = ScanCode.Keypad4 | ScanCodeMask,
            Keypad5 = ScanCode.Keypad5 | ScanCodeMask,
            Keypad6 = ScanCode.Keypad6 | ScanCodeMask,
            Keypad7 = ScanCode.Keypad7 | ScanCodeMask,
            Keypad8 = ScanCode.Keypad8 | ScanCodeMask,
            Keypad9 = ScanCode.Keypad9 | ScanCodeMask,
            Keypad0 = ScanCode.Keypad0 | ScanCodeMask,
            KeypadPeriod = ScanCode.KeypadPeriod | ScanCodeMask,

            Application = ScanCode.Application | ScanCodeMask,
            Power = ScanCode.Power | ScanCodeMask,

            KeypadEquals = ScanCode.KeypadEquals | ScanCodeMask,

            F13 = ScanCode.F13 | ScanCodeMask,
            F14 = ScanCode.F14 | ScanCodeMask,
            F15 = ScanCode.F15 | ScanCodeMask,
            F16 = ScanCode.F16 | ScanCodeMask,
            F17 = ScanCode.F17 | ScanCodeMask,
            F18 = ScanCode.F18 | ScanCodeMask,
            F19 = ScanCode.F19 | ScanCodeMask,
            F20 = ScanCode.F20 | ScanCodeMask,
            F21 = ScanCode.F21 | ScanCodeMask,
            F22 = ScanCode.F22 | ScanCodeMask,
            F23 = ScanCode.F23 | ScanCodeMask,
            F24 = ScanCode.F24 | ScanCodeMask,

            Execute = ScanCode.Execute | ScanCodeMask,
            Help = ScanCode.Help | ScanCodeMask,
            Menu = ScanCode.Menu | ScanCodeMask,
            Select = ScanCode.Select | ScanCodeMask,
            Stop = ScanCode.Stop | ScanCodeMask,
            Again = ScanCode.Again | ScanCodeMask,
            Undo = ScanCode.Undo | ScanCodeMask,
            Cut = ScanCode.Cut | ScanCodeMask,
            Copy = ScanCode.Copy | ScanCodeMask,
            Paste = ScanCode.Paste | ScanCodeMask,
            Find = ScanCode.Find | ScanCodeMask,
            Mute = ScanCode.Mute | ScanCodeMask,
            VolumeUp = ScanCode.VolumeUp | ScanCodeMask,
            VolumeDown = ScanCode.VolumeDown | ScanCodeMask,
            
            KeypadComma =  ScanCode.KeypadComma | ScanCodeMask,
            KeypadEqualsAs400 = ScanCode.KeypadEqualsAs400 | ScanCodeMask,

            AltErase = ScanCode.AltErase | ScanCodeMask,
            SysReq = ScanCode.SysReq | ScanCodeMask,
            Cancel = ScanCode.Cancel | ScanCodeMask,
            Clear = ScanCode.Clear | ScanCodeMask,
            Prior = ScanCode.Prior | ScanCodeMask,
            Return2 = ScanCode.Return2 | ScanCodeMask,
            Separator = ScanCode.Separator | ScanCodeMask,
            Out = ScanCode.Out | ScanCodeMask,
            Oper = ScanCode.Oper | ScanCodeMask,
            ClearAgain = ScanCode.ClearAgain | ScanCodeMask,
            Crsel = ScanCode.Crsel | ScanCodeMask,
            Exsel = ScanCode.Exsel | ScanCodeMask,

            Keypad00 = ScanCode.Keypad00 | ScanCodeMask,
            Keypad000 = ScanCode.Keypad000 | ScanCodeMask,
            ThousandsSeparator = ScanCode.ThousandsSeparator | ScanCodeMask,
            DecimalSeparator =  ScanCode.DecimalSeparator | ScanCodeMask,
            CurrencyUnit = ScanCode.CurrencyUnit | ScanCodeMask,
            CurrencySubUnit = ScanCode.CurrencySubUnit | ScanCodeMask,
            
            KeypadLeftParen = ScanCode.KeypadLeftParen | ScanCodeMask,
            KeypadRightParen = ScanCode.KeypadRightParen | ScanCodeMask,
            KeypadLeftBrace = ScanCode.KeypadLeftBrace | ScanCodeMask,
            KeypadRightBrace = ScanCode.KeypadRightBrace | ScanCodeMask,
            KeypadTab = ScanCode.KeypadTab | ScanCodeMask,
            KeypadBackspace = ScanCode.KeypadBackspace | ScanCodeMask,
            KeypadA = ScanCode.KeypadA | ScanCodeMask,
            KeypadB = ScanCode.KeypadB | ScanCodeMask,
            KeypadC = ScanCode.KeypadC | ScanCodeMask,
            KeypadD = ScanCode.KeypadD | ScanCodeMask,
            KeypadE = ScanCode.KeypadE | ScanCodeMask,
            KeypadF = ScanCode.KeypadF | ScanCodeMask,
            KeypadXOR = ScanCode.KeypadXOR | ScanCodeMask,
            KeypadPower = ScanCode.KeypadPower | ScanCodeMask,
            KeypadLess = ScanCode.KeypadLess | ScanCodeMask,
            KeypadGreater = ScanCode.KeypadGreater | ScanCodeMask,
            KeypadAmpersand = ScanCode.KeypadAmpersand | ScanCodeMask,
            KeypadDBLAmpersand = ScanCode.KeypadDBLAmpersand | ScanCodeMask,
            KeypadVerticalBar = ScanCode.KeypadVerticalBar | ScanCodeMask,
            KeypadDBLVerticalBar = ScanCode.KeypadDBLVerticalBar | ScanCodeMask,
            KeypadColon = ScanCode.KeypadColon | ScanCodeMask,
            KeypadHash = ScanCode.KeypadHash | ScanCodeMask,
            KeypadSpace = ScanCode.KeypadSpace | ScanCodeMask,
            KeypadAt = ScanCode.KeypadAt | ScanCodeMask,
            KeypadExclam = ScanCode.KeypadExclam | ScanCodeMask,
            KeypadMemStore = ScanCode.KeypadMemStore | ScanCodeMask,
            KeypadMemRecall = ScanCode.KeypadMemRecall | ScanCodeMask,
            KeypadMemAdd = ScanCode.KeypadMemAdd | ScanCodeMask,
            KeypadMemSubtract = ScanCode.KeypadMemSubtract | ScanCodeMask,
            KeypadMemMultiply = ScanCode.KeypadMemMultiply | ScanCodeMask,
            KeypadMemDivide =  ScanCode.KeypadMemDivide | ScanCodeMask,
            KeypadPlusMinus = ScanCode.KeypadPlusMinus | ScanCodeMask,
            KeypadClear = ScanCode.KeypadClear | ScanCodeMask,
            KeypadClearEntry = ScanCode.KeypadClearEntry | ScanCodeMask,
            KeypadBinary = ScanCode.KeypadBinary | ScanCodeMask,
            KeypadOctal = ScanCode.KeypadOctal | ScanCodeMask,
            KeypadDecimal = ScanCode.KeypadDecimal | ScanCodeMask,
            KeypadHexadecimal = ScanCode.KeypadHexadecimal | ScanCodeMask,

            LeftCtrl = ScanCode.LeftCtrl | ScanCodeMask,
            LeftShift = ScanCode.LeftShift | ScanCodeMask,
            LeftAlt = ScanCode.LeftAlt | ScanCodeMask,
            LeftGUI = ScanCode.LeftGUI | ScanCodeMask,
            RightCtrl = ScanCode.RightCtrl | ScanCodeMask,
            RightShift = ScanCode.RightShift | ScanCodeMask,
            RightAlt = ScanCode.RightAlt | ScanCodeMask,
            RightGUI = ScanCode.RightGUI | ScanCodeMask,

            Mode = ScanCode.Mode | ScanCodeMask,

            AudioNext = ScanCode.AudioNext | ScanCodeMask,
            AudioPrevious = ScanCode.AudioPrevious | ScanCodeMask,
            AudioStop = ScanCode.AudioStop | ScanCodeMask,
            AudioPlay = ScanCode.AudioPlay | ScanCodeMask,
            AudioMute = ScanCode.AudioMute | ScanCodeMask,
            MediaSelect = ScanCode.MediaSelect | ScanCodeMask,

            WWW = ScanCode.WWW | ScanCodeMask,
            Mail = ScanCode.Mail | ScanCodeMask,
            Calculator = ScanCode.Calculator | ScanCodeMask,
            Computer = ScanCode.Computer | ScanCodeMask,

            ACSearch = ScanCode.ACSearch | ScanCodeMask,
            ACHome = ScanCode.ACHome | ScanCodeMask,
            ACBack = ScanCode.ACBack | ScanCodeMask,
            ACForward = ScanCode.ACForward | ScanCodeMask,
            ACStop = ScanCode.ACStop | ScanCodeMask,
            ACRefresh = ScanCode.ACRefresh | ScanCodeMask,
            ACBookmarks = ScanCode.ACBookmarks | ScanCodeMask,

            BrightnessDown = ScanCode.BrightnessDown | ScanCodeMask,
            BrightnessUp = ScanCode.BrightnessUp | ScanCodeMask,
            DisplaySwitch = ScanCode.DisplaySwitch | ScanCodeMask,
            KBDIllumToggle = ScanCode.KBDIllumToggle | ScanCodeMask,
            KBDIllumDown =  ScanCode.KBDIllumDown | ScanCodeMask,
            KBDIllumUp = ScanCode.KBDIllumUp | ScanCodeMask,

            Eject = ScanCode.Eject | ScanCodeMask,
            Sleep = ScanCode.Sleep | ScanCodeMask,

            App1 = ScanCode.App1 | ScanCodeMask,
            App2 = ScanCode.App2 | ScanCodeMask,

            AudioRewind = ScanCode.AudioRewind | ScanCodeMask,
            AudioFastForward = ScanCode.AudioFastForward | ScanCodeMask,

            SoftLeft = ScanCode.SoftLeft | ScanCodeMask,
            SoftRight = ScanCode.SoftRight | ScanCodeMask,
            Call = ScanCode.Call | ScanCodeMask,
            EndCall = ScanCode.EndCall | ScanCodeMask,
        }

        [Flags]
        public enum KeyMod : ushort
        {
            None = 0x0000,
            LeftShift = 0x0001,
            RightShift = 0x0002,
            LeftControl = 0x0040,
            RightControl = 0x0080,
            LeftAlt = 0x0100,
            RightAlt = 0x0200,
            LeftGUI = 0x0400,
            RightGUI = 0x0800,
            Num = 0x1000,
            Caps =0x2000,
            Mode =0x4000,
            Scroll = 0x8000,

            Control = (LeftControl | RightControl),
            Shift = (LeftShift | RightShift),
            Alt = (LeftAlt | RightAlt),
            GUI = (LeftGUI | RightGUI),

            Reserved = Scroll
        }
    }
}
